---
- name: Install Apache
  package:
    name: apache2
    state: present

- name: Deploy index.html from template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Ensure Apache service is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- name: Check that Apache responds on port 80
  uri:
    url: http://localhost/
    status_code: 200

