---
- name: Install and enable tuned
  hosts: all
  become: yes
  tasks:
    - name: Install tuned package
      package:
        name: tuned
        state: present

    - name: Enable tuned service
      systemd:
        name: tuned
        enabled: yes
        state: started
